export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const SHOW_USER_DETAILS = 'SHOW_USER_DETAILS';
export const HIDE_USER_DETAILS = 'HIDE_USER_DETAILS';
export const DELETE_USER = 'DELETE_USER';
export const RECOVER_USER = 'RECOVER_USER';
